plugins {
    id("java-library")
    id("maven-publish")
    id("net.neoforged.moddev")
    id("org.jetbrains.kotlin.jvm")
    idea
}

val modId = property("mod_id").toString()

base {
    archivesName.set("$modId-neoforge")
}

repositories {
    mavenLocal()
    maven {
        name = "Kotlin for Forge"
        url = uri("https://thedarkcolour.github.io/KotlinForForge/")
    }
}

// Mojang ships Java 21 to end users in 1.21+
java.toolchain.languageVersion.set(JavaLanguageVersion.of(21))

neoForge {
    // Specify the version of NeoForge to use
    version = property("neo_version").toString()

    parchment {
        mappingsVersion = property("parchment_mappings_version").toString()
        minecraftVersion = property("parchment_minecraft_version").toString()
    }

    // Default run configurations
    runs {
        register("client") {
            client()
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        register("server") {
            server()
            programArgument("--nogui")
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        register("gameTestServer") {
            type = "gameTestServer"
            systemProperty("neoforge.enabledGameTestNamespaces", modId)
        }

        register("data") {
            clientData()
            programArguments.addAll(
                "--mod", modId,
                "--all",
                "--output", file("src/generated/resources/").absolutePath,
                "--existing", file("src/main/resources/").absolutePath
            )
        }

        configureEach {
            systemProperty("forge.logging.markers", "REGISTRIES")
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        register(modId) {
            sourceSet(sourceSets.main.get())
        }
    }
}

// Include resources generated by data generators
sourceSets.main.get().resources.srcDir("src/generated/resources")

// Local runtime configuration for optional dependencies
configurations {
    val localRuntime by creating
    named("runtimeClasspath") {
        extendsFrom(localRuntime)
    }
}

dependencies {
    // Kotlin for Forge - required for Kotlin language support in NeoForge
    implementation("thedarkcolour:kotlinforforge-neoforge:${property("kff_version")}")
    
    // Common module
    implementation(project(":common"))
}

// Process resources and expand properties
val generateModMetadata = tasks.register<ProcessResources>("generateModMetadata") {
    val replaceProperties = mapOf(
        "minecraft_version" to project.property("minecraft_version"),
        "minecraft_version_range" to project.property("minecraft_version_range"),
        "neo_version" to project.property("neo_version"),
        "neo_version_range" to project.property("neo_version_range"),
        "kff_version" to project.property("kff_version"),
        "kff_version_range" to project.property("kff_version_range"),
        "loader_version_range" to project.property("loader_version_range"),
        "mod_id" to modId,
        "mod_name" to project.property("mod_name"),
        "mod_license" to project.property("mod_license"),
        "mod_version" to project.property("mod_version"),
        "mod_authors" to project.property("mod_authors"),
        "mod_description" to project.property("mod_description")
    )
    inputs.properties(replaceProperties)
    expand(replaceProperties)
    from("src/main/templates")
    into(layout.buildDirectory.dir("generated/sources/modMetadata"))
}

sourceSets.main.get().resources.srcDir(generateModMetadata)
neoForge.ideSyncTask(generateModMetadata)

tasks.jar {
    from(project(":common").sourceSets.main.get().output)
}

// Publishing configuration
publishing {
    publications {
        register<MavenPublication>("mavenJava") {
            from(components["java"])
        }
    }
    repositories {
        maven {
            url = uri(layout.buildDirectory.dir("repo"))
        }
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
}

idea {
    module {
        isDownloadSources = true
        isDownloadJavadoc = true
    }
}
